import { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { RefreshCw, Radar, Flame, MapPin, Calendar, Compass, Hotel } from 'lucide-react';
import AnimatedSection from '../../shared/AnimatedSection';
import { STR } from './strings';
import { isVisaTarget, visaInfo } from './visaDestinations';
import HotFlights from './HotFlights';
import Explorer from './Explorer';
import PriceCalendar from './PriceCalendar';
import Hotels from './Hotels';
import Partners from './Partners';
import './TravelRadar3.css';

// Travel Radar 3.0 — live flight-price radar driven by public/radar.json
// (generated by scripts/fetch-radar.js on a cron). Isolated module: delete this
// folder + its route + header entry to roll back.
export default function TravelRadar3Page() {
    const { i18n } = useTranslation();
    const lang = i18n.language === 'ru' ? 'ru' : 'en';
    const s = STR[lang];
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState(null);

    useEffect(() => {
        let cancelled = false;
        setLoading(true);
        fetch('/radar.json', { cache: 'no-cache' })
            .then((r) => (r.ok ? r.json() : Promise.reject(new Error('no feed'))))
            .then((d) => { if (!cancelled) setData(d); })
            .catch(() => { if (!cancelled) setData(null); })
            .finally(() => { if (!cancelled) setLoading(false); });
        return () => { cancelled = true; };
    }, []);

    // Safety filter: keep ONLY visa-free / easy-visa destinations for RF
    // citizens and attach each destination's visa label. Runs over whatever the
    // feed contains, so the radar is correct even before the next cron rebuild.
    const view = useMemo(() => {
        if (!data) return null;
        const tag = (o, dest) => ({ ...o, visa: o.visa || visaInfo(dest) });
        const hotFlights = (data.hotFlights || [])
            .filter((f) => isVisaTarget(f.destination))
            .map((f) => tag(f, f.destination));
        const cheapFrom = (data.cheapFrom || [])
            .map((c) => ({
                ...c,
                items: (c.items || [])
                    .filter((it) => isVisaTarget(it.destination))
                    .map((it) => tag(it, it.destination)),
            }))
            .filter((c) => c.items.length > 0);
        const calendars = (data.calendars || [])
            .filter((c) => isVisaTarget(c.destination))
            .map((c) => tag(c, c.destination));
        return { hotFlights, cheapFrom, calendars };
    }, [data]);

    const updated = data?.updatedAt ? new Date(data.updatedAt) : null;
    const updatedLabel = updated && !Number.isNaN(updated.getTime())
        ? updated.toLocaleString(lang === 'ru' ? 'ru-RU' : 'en-US', {
            day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit',
        })
        : '';

    return (
        <div className="radar3">
            <div className="container">
                <AnimatedSection>
                    <div className="radar3-header">
                        <h1>
                            <Radar size={26} aria-hidden="true" /> {s.pageTitle}
                            <span className="radar3-badge3">🌍 {s.visaTag}</span>
                        </h1>
                        <p className="radar3-sub">{s.subtitle}</p>
                        <p className="radar3-metaline">
                            {updatedLabel && (
                                <span><RefreshCw size={13} aria-hidden="true" /> {s.updated}: {updatedLabel}</span>
                            )}
                            <span className="radar3-src">{s.source}</span>
                        </p>
                    </div>
                </AnimatedSection>

                {loading ? (
                    <div className="radar3-loading">{s.loading}</div>
                ) : !data ? (
                    <div className="radar3-loading">{s.noData}</div>
                ) : (
                    <>
                        <AnimatedSection delay={0.05}>
                            <section className="radar3-panel">
                                <div className="radar3-sec-head">
                                    <Flame size={18} aria-hidden="true" />
                                    <h2>{s.hotTitle}</h2>
                                </div>
                                <p className="radar3-sec-desc">{s.hotDesc}</p>
                                <HotFlights items={view.hotFlights} lang={lang} s={s} />
                            </section>
                        </AnimatedSection>

                        <AnimatedSection delay={0.05}>
                            <section className="radar3-panel">
                                <div className="radar3-sec-head">
                                    <MapPin size={18} aria-hidden="true" />
                                    <h2>{s.cheapTitle}</h2>
                                </div>
                                <p className="radar3-sec-desc">{s.cheapDesc}</p>
                                <Explorer cities={view.cheapFrom} lang={lang} s={s} />
                            </section>
                        </AnimatedSection>

                        {view.calendars && view.calendars.length > 0 && (
                            <AnimatedSection delay={0.05}>
                                <section className="radar3-panel">
                                    <div className="radar3-sec-head">
                                        <Calendar size={18} aria-hidden="true" />
                                        <h2>{s.calTitle}</h2>
                                    </div>
                                    <p className="radar3-sec-desc">{s.calDesc}</p>
                                    <PriceCalendar calendars={view.calendars} lang={lang} s={s} />
                                </section>
                            </AnimatedSection>
                        )}

                        <AnimatedSection delay={0.05}>
                            <section className="radar3-panel">
                                <div className="radar3-sec-head">
                                    <Compass size={18} aria-hidden="true" />
                                    <h2>{s.partnersTitle}</h2>
                                </div>
                                <p className="radar3-sec-desc">{s.partnersDesc}</p>
                                <div className="radar3-pgroup__head radar3-hotels-head">
                                    <Hotel size={16} aria-hidden="true" />
                                    <span>{s.hotelsByDest}</span>
                                </div>
                                <Hotels lang={lang} s={s} />
                                <Partners lang={lang} />
                            </section>
                        </AnimatedSection>

                        <p className="radar3-disclaimer">{s.disclaimer}</p>
                    </>
                )}
            </div>
        </div>
    );
}
