import { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { RefreshCw, Radar, Flame, MapPin, Calendar, Compass, Hotel } from 'lucide-react';
import AnimatedSection from '../../shared/AnimatedSection';
import { STR } from './strings';
import HotFlights from './HotFlights';
import CheapFrom from './CheapFrom';
import PriceCalendar from './PriceCalendar';
import Partners from './Partners';
import WidgetEmbed from './WidgetEmbed';
import './TravelRadar3.css';

// Hotel-selection widget (Yandex Travel via Travelpayouts) — renders live hotel
// offers WITH prices. Generated in the dashboard (its promo_id/campaign_id are
// account-minted); shmarker/trs are ours. Responsive.
const HOTELS_WIDGET_SRC =
    'https://tpemd.com/content?trs=547927&shmarker=748397&locale=ru&sort_by=-score' +
    '&powered_by=true&min_lines=5&responsive=true&promo_id=7453&campaign_id=193';

// Travel Radar 3.0 — live flight-price radar driven by public/radar.json
// (generated by scripts/fetch-radar.js on a cron). Isolated module: delete this
// folder + its route + header entry to roll back.
export default function TravelRadar3Page() {
    const { i18n } = useTranslation();
    const lang = i18n.language === 'ru' ? 'ru' : 'en';
    const s = STR[lang];
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState(null);

    useEffect(() => {
        let cancelled = false;
        setLoading(true);
        fetch('/radar.json', { cache: 'no-cache' })
            .then((r) => (r.ok ? r.json() : Promise.reject(new Error('no feed'))))
            .then((d) => { if (!cancelled) setData(d); })
            .catch(() => { if (!cancelled) setData(null); })
            .finally(() => { if (!cancelled) setLoading(false); });
        return () => { cancelled = true; };
    }, []);

    const updated = data?.updatedAt ? new Date(data.updatedAt) : null;
    const updatedLabel = updated && !Number.isNaN(updated.getTime())
        ? updated.toLocaleString(lang === 'ru' ? 'ru-RU' : 'en-US', {
            day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit',
        })
        : '';

    return (
        <div className="radar3">
            <div className="container">
                <AnimatedSection>
                    <div className="radar3-header">
                        <h1>
                            <Radar size={26} aria-hidden="true" /> {s.pageTitle}
                            <span className="radar3-badge3">3.0</span>
                        </h1>
                        <p className="radar3-sub">{s.subtitle}</p>
                        <p className="radar3-metaline">
                            {updatedLabel && (
                                <span><RefreshCw size={13} aria-hidden="true" /> {s.updated}: {updatedLabel}</span>
                            )}
                            <span className="radar3-src">{s.source}</span>
                        </p>
                    </div>
                </AnimatedSection>

                {loading ? (
                    <div className="radar3-loading">{s.loading}</div>
                ) : !data ? (
                    <div className="radar3-loading">{s.noData}</div>
                ) : (
                    <>
                        <AnimatedSection delay={0.05}>
                            <section className="radar3-panel">
                                <div className="radar3-sec-head">
                                    <Flame size={18} aria-hidden="true" />
                                    <h2>{s.hotTitle}</h2>
                                </div>
                                <p className="radar3-sec-desc">{s.hotDesc}</p>
                                <HotFlights items={data.hotFlights} lang={lang} s={s} />
                            </section>
                        </AnimatedSection>

                        <AnimatedSection delay={0.05}>
                            <section className="radar3-panel">
                                <div className="radar3-sec-head">
                                    <MapPin size={18} aria-hidden="true" />
                                    <h2>{s.cheapTitle}</h2>
                                </div>
                                <p className="radar3-sec-desc">{s.cheapDesc}</p>
                                <CheapFrom cities={data.cheapFrom} lang={lang} s={s} />
                            </section>
                        </AnimatedSection>

                        {data.calendars && data.calendars.length > 0 && (
                            <AnimatedSection delay={0.05}>
                                <section className="radar3-panel">
                                    <div className="radar3-sec-head">
                                        <Calendar size={18} aria-hidden="true" />
                                        <h2>{s.calTitle}</h2>
                                    </div>
                                    <p className="radar3-sec-desc">{s.calDesc}</p>
                                    <PriceCalendar calendars={data.calendars} lang={lang} s={s} />
                                </section>
                            </AnimatedSection>
                        )}

                        <AnimatedSection delay={0.05}>
                            <section className="radar3-panel">
                                <div className="radar3-sec-head">
                                    <Compass size={18} aria-hidden="true" />
                                    <h2>{s.partnersTitle}</h2>
                                </div>
                                <p className="radar3-sec-desc">{s.partnersDesc}</p>
                                <div className="radar3-hsearch">
                                    <div className="radar3-pgroup__head">
                                        <Hotel size={16} aria-hidden="true" />
                                        <span>{s.hotelPricesLabel}</span>
                                    </div>
                                    <WidgetEmbed src={HOTELS_WIDGET_SRC} initialHeight={460} />
                                </div>
                                <Partners lang={lang} />
                            </section>
                        </AnimatedSection>

                        <p className="radar3-disclaimer">{s.disclaimer}</p>
                    </>
                )}
            </div>
        </div>
    );
}
