// Self-contained RU/EN strings for the Travel Radar v2.0 (Concierge) module.
// Kept inside this folder on purpose: deleting the folder fully removes v2 with
// no orphan keys left in the shared locale files.

const RU = {
  badge: 'v2.0 · бета',
  heroTitle: 'Радар Путешествий 2.0 — Консьерж',
  heroLead: 'Не просто находим выгодное предложение — помогаем забронировать и оплатить, даже если зарубежный сайт не принимает российскую карту. Вы платите в рублях (Мир, СБП), остальное берём на себя.',
  ctaFreeForm: 'Нашёл сам — помогите оплатить',
  ctaMyRequests: 'Мои заявки',
  howTitle: 'Как это работает',
  how: [
    'Оставляете заявку: с карточки горящего предложения или вставляете свою ссылку.',
    'Оператор подбирает и присылает котировку с итоговой ценой в рублях.',
    'Оплачиваете привычным способом (Мир, СБП). Мы бронируем и оплачиваем поставщику.',
    'Получаете билеты и ваучеры в личном кабинете.',
  ],
  feedTitle: 'Горящие предложения',
  feedLead: 'Живой фид из Telegram-каналов. На любом — кнопка «Оформить через консьерж».',
  conciergeCta: 'Оформить через консьерж',
  loading: 'Загружаем предложения…',
  noFeed: 'Фид временно недоступен. Вы можете оставить свободную заявку.',
  openTelegram: 'Оригинал в Telegram',

  // form
  formTitle: 'Заявка на консьерж-сопровождение',
  formFreeTitle: 'Свободная заявка — «нашёл сам»',
  fType: 'Тип',
  types: { air: 'Авиа', tour: 'Тур', hotel: 'Отель', combo: 'Комбо' },
  fRoute: 'Направление / маршрут',
  fRoutePh: 'Например: Москва → Пхукет',
  fExternal: 'Ссылка или описание найденного варианта',
  fExternalPh: 'Вставьте ссылку на предложение или опишите его',
  fFlex: 'Гибкость дат',
  flex: { exact: 'Точные даты', range: 'Диапазон', tomorrow: 'Готов лететь завтра' },
  fDeparture: 'Город вылета',
  departures: { spb: 'Санкт-Петербург', msk: 'Москва', other: 'Другой' },
  fPassengers: 'Пассажиры',
  fAdults: 'Взрослые',
  fKids: 'Дети',
  fBudget: 'Бюджет / ожидаемая цена',
  fBudgetPh: '₽',
  fUrgency: 'Срочность',
  urgency: { hot: 'Горящее', week: 'В течение недели', flex: 'Гибко' },
  fContact: 'Контакт для связи',
  fContactPh: 'Telegram / телефон / email',
  fChannel: 'Канал связи',
  channels: { web: 'Чат на сайте', telegram: 'Telegram', email: 'Email' },
  consent: 'Согласен с офертой и обработкой персональных данных',
  attachedDeal: 'Прикреплённое предложение',
  submit: 'Отправить заявку',
  cancel: 'Отмена',
  needConsent: 'Нужно согласие с офертой',
  needRoute: 'Укажите маршрут или ссылку',
  needContact: 'Укажите контакт для связи',
  created: 'Заявка создана! Оператор ответит в рабочие часы (обычно до 2 ч).',

  // cabinet
  cabinetTitle: 'Мои заявки',
  cabinetEmpty: 'Заявок пока нет. Оставьте первую — с карточки предложения или свободную.',
  request: 'Заявка',
  timeline: 'Статусы',
  chat: 'Чат с оператором',
  chatPh: 'Сообщение…',
  send: 'Отправить',
  you: 'Вы',
  operator: 'Оператор',
  demoAdvance: 'демо: следующий статус',
  cancelRequest: 'Отменить заявку',
  source: { radar_deal: 'из фида', video_landing: 'из видео', free_form: 'свободная' },

  statuses: {
    new: 'Создана',
    assigned: 'Взята оператором',
    clarifying: 'Уточняем детали',
    quoting: 'Подбираем',
    quote_sent: 'Котировка отправлена',
    quote_accepted: 'Котировка принята',
    awaiting_payment: 'Ждём оплату',
    paid: 'Оплачено',
    booking: 'Бронируем',
    booked: 'Забронировано',
    completed: 'Завершено',
    cancelled: 'Отменена',
  },
  // auto operator messages shown when the (demo) status advances
  autoMsg: {
    assigned: 'Здравствуйте! Взял вашу заявку в работу.',
    clarifying: 'Уточните, пожалуйста, удобные даты и пожелания.',
    quoting: 'Подбираю лучшие варианты под ваш запрос.',
    quote_sent: 'Готова котировка: итоговая цена в рублях с учётом сервисной комиссии. Подтвердите?',
    quote_accepted: 'Отлично, фиксирую котировку.',
    awaiting_payment: 'Выставил счёт — оплатите по ссылке (Мир/СБП).',
    paid: 'Оплата получена, спасибо! Перехожу к бронированию.',
    booking: 'Бронирую и оплачиваю поставщику.',
    booked: 'Готово! Билеты и ваучеры — в разделе документов.',
    completed: 'Заявка закрыта. Хорошей поездки!',
  },
  legalNote: 'Memora оказывает услугу подбора и сопровождения; продавцом турпродукта не является. Оплата сервисной комиссии — по оферте.',
};

const EN = {
  badge: 'v2.0 · beta',
  heroTitle: 'Travel Radar 2.0 — Concierge',
  heroLead: 'We don’t just find a great deal — we help you book and pay for it, even when a foreign site won’t accept a Russian card. You pay in rubles (Mir, SBP); we handle the rest.',
  ctaFreeForm: 'I found it myself — help me pay',
  ctaMyRequests: 'My requests',
  howTitle: 'How it works',
  how: [
    'Submit a request: from a hot-deal card, or paste your own link.',
    'An operator finds options and sends a quote with the final ruble price.',
    'You pay the usual way (Mir, SBP). We book and pay the supplier.',
    'You get tickets and vouchers in your account.',
  ],
  feedTitle: 'Hot deals',
  feedLead: 'A live feed from Telegram channels. Every item has a “Book via concierge” button.',
  conciergeCta: 'Book via concierge',
  loading: 'Loading deals…',
  noFeed: 'The feed is temporarily unavailable. You can still submit a free-form request.',
  openTelegram: 'Original in Telegram',

  formTitle: 'Concierge request',
  formFreeTitle: 'Free-form request — “I found it myself”',
  fType: 'Type',
  types: { air: 'Flight', tour: 'Tour', hotel: 'Hotel', combo: 'Combo' },
  fRoute: 'Destination / route',
  fRoutePh: 'e.g. Moscow → Phuket',
  fExternal: 'Link or description of what you found',
  fExternalPh: 'Paste a link to the offer or describe it',
  fFlex: 'Date flexibility',
  flex: { exact: 'Exact dates', range: 'Range', tomorrow: 'Ready to fly tomorrow' },
  fDeparture: 'Departure city',
  departures: { spb: 'Saint Petersburg', msk: 'Moscow', other: 'Other' },
  fPassengers: 'Passengers',
  fAdults: 'Adults',
  fKids: 'Children',
  fBudget: 'Budget / expected price',
  fBudgetPh: '₽',
  fUrgency: 'Urgency',
  urgency: { hot: 'Hot', week: 'Within a week', flex: 'Flexible' },
  fContact: 'Contact',
  fContactPh: 'Telegram / phone / email',
  fChannel: 'Preferred channel',
  channels: { web: 'Web chat', telegram: 'Telegram', email: 'Email' },
  consent: 'I accept the terms and personal-data processing',
  attachedDeal: 'Attached deal',
  submit: 'Submit request',
  cancel: 'Cancel',
  needConsent: 'Consent is required',
  needRoute: 'Enter a route or a link',
  needContact: 'Enter a contact',
  created: 'Request created! An operator will reply during business hours (usually within 2h).',

  cabinetTitle: 'My requests',
  cabinetEmpty: 'No requests yet. Submit your first — from a deal card or free-form.',
  request: 'Request',
  timeline: 'Status',
  chat: 'Chat with operator',
  chatPh: 'Message…',
  send: 'Send',
  you: 'You',
  operator: 'Operator',
  demoAdvance: 'demo: next status',
  cancelRequest: 'Cancel request',
  source: { radar_deal: 'from feed', video_landing: 'from video', free_form: 'free-form' },

  statuses: {
    new: 'Created',
    assigned: 'Assigned',
    clarifying: 'Clarifying',
    quoting: 'Sourcing',
    quote_sent: 'Quote sent',
    quote_accepted: 'Quote accepted',
    awaiting_payment: 'Awaiting payment',
    paid: 'Paid',
    booking: 'Booking',
    booked: 'Booked',
    completed: 'Completed',
    cancelled: 'Cancelled',
  },
  autoMsg: {
    assigned: 'Hi! I’ve picked up your request.',
    clarifying: 'Could you confirm your preferred dates and wishes?',
    quoting: 'Sourcing the best options for your request.',
    quote_sent: 'Here’s the quote: final ruble price incl. the service fee. Confirm?',
    quote_accepted: 'Great, locking in the quote.',
    awaiting_payment: 'Invoice sent — pay via the link (Mir/SBP).',
    paid: 'Payment received, thank you! Moving to booking.',
    booking: 'Booking and paying the supplier.',
    booked: 'Done! Tickets and vouchers are in your documents.',
    completed: 'Request closed. Have a great trip!',
  },
  legalNote: 'Memora provides a search & assistance service and is not the seller of the travel product. The service fee is charged per the terms.',
};

export function getStrings(lang) {
  return lang === 'en' ? EN : RU;
}
